---

- name: Show usage metric collection disclaimer
  debug:
    msg: |
      By continuing with the ongoing installation process,
      you are giving your consent for the collection of usage metrics
      mentioned at https://immunity.io/docs/user/usage-metric-collection.html

      If you prefer not to participate, you can opt-out by setting
      "immunity22_usage_metric_collection: false" in your playbook.
      However, before making that decision, we encourage you to explore how this
      information contributes to the enhancement of Immunity at the following link:
      https://immunity.io/docs/user/usage-metric-collection.html

      Should you wish to support us through data collection but prefer to disable
      this disclaimer, you can do so by setting
      "immunity22_usage_metric_collection: true" in your playbook.
  when: "immunity22_usage_metric_collection == None"

- name: Ensure user has enough time to read
  pause:
    seconds: 13
  when: "immunity22_usage_metric_collection == None"
