---

- name: Upload generate_django_secret_key.py script
  copy:
    src: generate_django_secret_key.py
    dest: "{{ immunity22_path }}/generate_django_secret_key.py"
    mode: 0754

- name: Generate new django SECRET_KEY
  shell: "{{ virtualenv_path }}/bin/python ./generate_django_secret_key.py > .django-secret-key"
  args:
    chdir: "{{ immunity22_path }}"
    creates: "{{ immunity22_path }}/.django-secret-key"

- name: Get django SECRET_KEY
  command: "cat .django-secret-key"
  register: secret_key
  changed_when: false
  args:
    chdir: "{{ immunity22_path }}"

- name: Set permission to secret key file
  file:
    dest: "{{ immunity22_path }}/.django-secret-key"
    mode: 0600

- name: Set secret_key fact
  set_fact: immunity22_secret_key="{{ secret_key.stdout }}"
