---

- import_tasks: consent.yml
  tags: [immunity22, usage_collection]

- import_tasks: apt.yml
  tags: [immunity22, apt]

- import_tasks: ssh.yml
  tags: [immunity22, ssh]

- name: Import system tasks
  import_tasks: system.yml
  tags: [immunity22, system]

- import_tasks: pip.yml
  tags: [immunity22, pip]

# comprises django_secret_key.yml
- import_tasks: django.yml
  tags: [immunity22, django]

- import_tasks: freeradius.yml
  when: immunity22_radius and immunity22_freeradius_install
  tags: [immunity22, freeradius]

- import_tasks: supervisor.yml
  tags: [immunity22, supervisor]

- import_tasks: nginx.yml
  when: immunity22_nginx_install
  tags: [immunity22, nginx]

- import_tasks: cron.yml
  tags: [immunity22, cron]

- import_tasks: complete.yml
  tags: [immunity22]
