---
- name: Set nginx max upload size
  # Required to allow uploading firmware images
  set_fact:
    immunity22_nginx_client_max_body_size: "{{ immunity22_firmware_upgrader_max_file_size }}"
  when: immunity22_firmware_upgrader

- name: Create "{{ immunity22_path }}/public_html"
  file:
    path: "{{ immunity22_path }}/public_html"
    state: directory
    mode: 0775

- name: Create "{{ immunity22_path }}/nginx-conf/immunity22"
  file:
    path: "{{ immunity22_path }}/nginx-conf/immunity22"
    state: directory
    mode: 0770

- name: Create "{{ immunity22_path }}/ssl"
  file:
    path: "{{ immunity22_path }}/ssl"
    state: directory
    mode: 0770

- name: Create SSL cert if not exists yet
  command: >
    openssl req -new -nodes -x509 \
    -subj "/C={{ immunity22_ssl_country }}/ST={{ immunity22_ssl_state }} \
           /L={{ immunity22_ssl_locality }}/O={{ immunity22_ssl_organization }} \
           /CN={{ immunity22_ssl_common_name }}" \
    -days 3650 \
    -keyout {{ immunity22_ssl_key }} \
    -out {{ immunity22_ssl_cert }} \
    -extensions v3_ca creates={{ immunity22_ssl_cert }}
  notify: Restart nginx

- name: Copy SSL cert to be added to trusted Cert (for freeradius)
  copy:
    src: "{{ immunity22_ssl_cert }}"
    dest: /usr/local/share/ca-certificates/openwisp-ssl-server.crt
    remote_src: true
    owner: "root"
    group: "root"
    mode: "0644"
  notify: Update-ca-certificates

- name: Disable default nginx configuration
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: Nginx SSL configuration
  template:
    src: nginx/ssl-conf.j2
    dest: "{{ immunity22_path }}/nginx-conf/immunity22/ssl.conf"
    mode: 0644
  notify: Restart nginx

- name: Nginx security configuration
  template:
    src: nginx/security-conf.j2
    dest: "{{ immunity22_path }}/nginx-conf/immunity22/security.conf"
    mode: 0644
  notify: Restart nginx
  tags: [nginx_security]

- name: Nginx site available
  template:
    src: nginx/site-conf.j2
    dest: "/etc/nginx/sites-available/{{ inventory_hostname }}"
    mode: 0644
  notify: Restart nginx

- name: Nginx site enabled
  file:
    src: "/etc/nginx/sites-available/{{ inventory_hostname }}"
    dest: "/etc/nginx/sites-enabled/{{ inventory_hostname }}"
    state: link
  notify: Restart nginx

- name: Configure nginx log rotation
  template:
    src: logrotate.d/openwisp-nginx.j2
    dest: /etc/logrotate.d/openwisp-nginx
    mode: 0644

- name: Disable nginx server tokens
  replace:
    path: /etc/nginx/nginx.conf
    regexp: '#(\s+)server_tokens off'
    replace: 'server_tokens off'
    backup: true
  notify: Restart nginx
