---

- name: Template for uwsgi.ini
  template:
    src: uwsgi.ini.j2
    dest: "{{ immunity22_path }}/uwsgi.ini"
    mode: 0644
  notify: Update supervisor configuration

- name: Template for supervisor uwsgi
  template:
    src: supervisor/immunity22.j2
    dest: "{{ supervisor_path | format('immunity22') }}"
    mode: 0644
  notify: Update supervisor configuration

- name: Template for supervisor daphne
  template:
    src: supervisor/daphne.j2
    dest: "{{ supervisor_path | format('daphne') }}"
    mode: 0644
  when: immunity22_daphne_install
  notify: Update supervisor configuration

- name: Template for supervisor celery
  template:
    src: supervisor/celery.j2
    dest: "{{ supervisor_path | format('celery') }}"
    mode: 0644
  notify: Update supervisor configuration
  tags: [celery_conf]

- name: Template for supervisor celery network
  template:
    src: supervisor/celery_network.j2
    dest: "{{ supervisor_path | format('celery_network') }}"
    mode: 0644
  when: immunity22_celery_network
  notify: Update supervisor configuration
  tags: [celery_conf]

- name: Template for supervisor celery firmware_upgrader
  template:
    src: supervisor/celery_firmware_upgrader.j2
    dest: "{{ supervisor_path | format('celery_firmware_upgrader') }}"
    mode: 0644
  when: immunity22_firmware_upgrader and immunity22_celery_firmware_upgrader
  notify: Update supervisor configuration
  tags: [celery_conf]

- name: Template for supervisor celery monitoring
  template:
    src: supervisor/celery_monitoring.j2
    dest: "{{ supervisor_path | format('celery_monitoring') }}"
    mode: 0644
  when: immunity22_monitoring and immunity22_celery_monitoring
  notify: Update supervisor configuration
  tags: [celery_conf]

- name: Template for supervisor celerybeat
  template:
    src: supervisor/celerybeat.j2
    dest: "{{ supervisor_path | format('celerybeat') }}"
    mode: 0644
  when: immunity22_celerybeat
  notify: Update supervisor configuration
  tags: [celery_conf]

- name: Remove supervisor runworker.conf (obsolete)
  file:
    dest: "{{ supervisor_path | format('runworker') }}"
    state: absent
  notify: Update supervisor configuration
