---

- name: Converge
  hosts: all
  become: true

  vars:
    immunity22_network_topology: true
    immunity22_firmware_upgrader: true
    immunity22_radius: true
    immunity22_controller_subnet_division: true
    immunity22_uwsgi_extra_conf: |
      single-interpreter=True
    immunity22_usage_metric_collection: false

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Remove the .dockerenv file
      file:
        path: /.dockerenv
        state: absent

  roles:
    - role: immunity.immunity22
