---

- src: https://github.com/Stouts/Stouts.postfix
  version: origin/develop
  name: Stouts.postfix

- src: https://github.com/edge-servers/ansible-im-influxdb
  version: origin/master
  name: edge-servers.influxdb
