---

- src: https://github.com/Stouts/Stouts.postfix
  version: origin/develop
  name: Stouts.postfix

- src: https://github.com/edge-servers/ansible-ow-influxdb
  version: origin/master
  name: immunity.influxdb
