---

- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Run a specific subset of tests
      command: >
        /opt/immunity22/env/bin/python /opt/immunity22/manage.py test --keepdb --exclude skip_prod \
            immunity_controller.pki.tests.test_admin \
            immunity_controller.pki.tests.test_models \
            immunity_controller.config.tests.test_tag \
            immunity_controller.config.tests.test_vpn \
            immunity_controller.config.tests.test_admin.TestAdmin.test_preview_device \
            immunity_controller.config.tests.test_admin.TestAdmin.test_device_preview_button \
            immunity_controller.config.tests.test_admin.TestAdmin.test_template_preview_button \
            immunity_controller.config.tests.test_admin.TestAdmin.test_vpn_preview_button \
            immunity_controller.config.tests.test_admin.TestAdmin.test_device_queryset \
            immunity_controller.config.tests.test_admin.TestAdmin.test_device_organization_fk_autocomplete_view \
            immunity_controller.config.tests.test_admin.TestAdmin.test_device_templates_m2m_queryset \
            immunity_controller.config.tests.test_admin.TestAdmin.test_template_queryset \
            immunity_controller.config.tests.test_admin.TestAdmin.test_template_organization_fk_autocomplete_view \
            immunity_controller.config.tests.test_admin.TestAdmin.test_template_vpn_fk_autocomplete_view \
            immunity_controller.config.tests.test_admin.TestAdmin.test_vpn_queryset \
            immunity_controller.config.tests.test_admin.TestAdmin.test_vpn_organization_fk_autocomplete_view \
            immunity_controller.config.tests.test_admin.TestAdmin.test_vpn_ca_fk_queryset \
            immunity_controller.config.tests.test_admin.TestAdmin.test_vpn_cert_fk_queryset \
            immunity_controller.config.tests.test_admin.TestAdmin.test_changelist_recover_deleted_button \
            immunity_controller.config.tests.test_admin.TestAdmin.test_recoverlist_operator_403 \
            immunity_controller.config.tests.test_admin.TestAdmin.test_device_template_filter \
            immunity_controller.config.tests.test_admin.TestAdmin.test_device_contains_default_templates_js \
            immunity_controller.config.tests.test_admin.TestAdmin.test_template_not_contains_default_templates_js \
            immunity_controller.config.tests.test_admin.TestAdmin.test_vpn_not_contains_default_templates_js \
            immunity_controller.config.tests.test_notifications \
            immunity_controller.subnet_division.tests.test_models \
            immunity_notifications.tests.test_admin.TestAdmin
      changed_when: false

    - name: Check if redis-server is running
      command: systemctl status redis-server
      changed_when: false

    - name: Chcke if redis is running
      command: systemctl status redis
      changed_when: false

    - name: Check Immunity
      block:
        - name: Check if Immunity is running
          uri:
            url: "https://{{ inventory_hostname }}/admin/login/?next=/admin/"
            validate_certs: false
      rescue:
        - name: Get Immunity log
          command: "tail -n 500 {{ immunity22_path }}/log/*.log"
          register: immunity_log

        - name: Show Immunity log
          debug:
            var: immunity_log
