---

- name: Update supervisor configuration
  command: supervisorctl update all
  register: supervisord_update_all

- name: Reload application
  debug:
    msg: "Restarting application services"
  changed_when: true
  notify:
    - Reload uwsgi
    - Restart daphne
    - Restart other supervisor managed services
    - Remove celerybeat schedule
    - Migrate timeseries database

- name: Reload uwsgi
  command: "{{ virtualenv_path }}/bin/uwsgi --reload {{ immunity22_path }}/uwsgi.pid"
  # Skips reloading uwsgi if it's supervisor configuration has changed.
  # Otherwise, the process will be restarted twice.
  when: not (supervisord_update_all is defined and "immunity22:" in supervisord_update_all.stdout)

# Daphne does not support graceful reloading.
# Read https://github.com/django/daphne/issues/177
- name: Restart daphne
  command: "supervisorctl restart daphne:asgi0"
  # Skips restarting daphne if it's supervisor configuration has changed.
  # Otherwise, the process will be restarted twice.
  when: not (supervisord_update_all is defined and "daphne:" in supervisord_update_all.stdout)

- name: Restart other supervisor managed services
  command: "supervisorctl restart {{ item.name }}"
  # Skips restarting service if it's supervisor configuration has changed.
  # Otherwise, the process will be restarted twice.
  when: "item.when and not (supervisord_update_all is defined and item.name ~ ':' in supervisord_update_all.stdout)"
  loop: "{{ immunity22_default_supervisor_restart + immunity22_extra_supervisor_restart }}"
  loop_control:
    loop_var: item

# Clean up the schedule file because it may become corrupted after updates
- name: Remove celerybeat schedule
  file:
    path: "{{ immunity22_path }}/celerybeat-schedule.db"
    state: absent

# NOTE: Related to https://github.com/edge-servers/immunity-monitoring/pull/368
# TODO: Remove this when immunity-monitoring 1.1.0 is released
- name: Migrate timeseries database
  become: true
  become_user: "{{ www_user }}"
  django_manage:
    app_path: "{{ immunity22_path }}"
    command: migrate_timeseries
    virtualenv: "{{ virtualenv_path }}"
  when: immunity22_monitoring

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  when: immunity22_nginx_install

- name: Start redis
  when: immunity22_redis_install
  service:
    name: redis
    state: started

- name: Update-ca-certificates
  command: /usr/sbin/update-ca-certificates

- name: Restart freeradius
  service:
    name: freeradius
    state: started
